services:
  postgres:
    image: postgres:16-alpine
    container_name: telehubx-pg
    environment:
      POSTGRES_USER: telehubx
      POSTGRES_PASSWORD: telehubx
      POSTGRES_DB: telehubx
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: telehubx-redis
    ports:
      - "6386:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
